# Generated by Django 4.2.7 on 2023-11-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('Name', models.CharField(max_length=200)),
                ('Type1', models.CharField(choices=[('Normal', 'Normal'), ('Electric', 'Electric'), ('Grass', 'Grass'), ('Poison', 'Poison'), ('Water', 'Water'), ('Ice', 'Ice'), ('Fire', 'Fire'), ('Bug', 'Bug'), ('Flying', 'Flying'), ('Rock', 'Rock'), ('Ground', 'Ground'), ('Fighting', 'Fighting'), ('Psychic', 'Psychic'), ('Ghost', 'Ghost'), ('Dragon', 'Dragon')], max_length=8)),
                ('Type2', models.CharField(choices=[('Normal', 'Normal'), ('Electric', 'Electric'), ('Grass', 'Grass'), ('Poison', 'Poison'), ('Water', 'Water'), ('Ice', 'Ice'), ('Fire', 'Fire'), ('Bug', 'Bug'), ('Flying', 'Flying'), ('Rock', 'Rock'), ('Ground', 'Ground'), ('Fighting', 'Fighting'), ('Psychic', 'Psychic'), ('Ghost', 'Ghost'), ('Dragon', 'Dragon')], max_length=8)),
                ('Weakness', models.CharField(choices=[('Normal', 'Normal'), ('Electric', 'Electric'), ('Grass', 'Grass'), ('Poison', 'Poison'), ('Water', 'Water'), ('Ice', 'Ice'), ('Fire', 'Fire'), ('Bug', 'Bug'), ('Flying', 'Flying'), ('Rock', 'Rock'), ('Ground', 'Ground'), ('Fighting', 'Fighting'), ('Psychic', 'Psychic'), ('Ghost', 'Ghost'), ('Dragon', 'Dragon')], max_length=8)),
            ],
        ),
    ]
